export const environment = {
  COOKIE_EXP_MINUTES: '__COOKIE_EXP_MINUTES__',
  COOKIE_SECRET: '__COOKIE_SECRET__',
  USER_COOKIE_NAME: '__SECURE_COOKIE__',
  GOOGLE_CLIENT_ID: '__GOOGLE_CLIENT_ID__',
};
